name = "aoc2024"
version = "0.1.0"
defaultTargets = ["day1", "day2"]

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "day1"
root = "Aoc2024.Day01.Main"

[[lean_exe]]
name = "day2"
root = "Aoc2024.Day02.Main"
