version: '3'

tasks:
  default: task --list
  build:
    desc: Build
    sources:
      - Aoc2024/**/*.lean
    generates:
      - .lake/build/bin/*
    cmds:
      - lake build
  day1:
    desc: Run day 1
    deps: [build]
    cmds: 
      - .lake/build/bin/day1
  day2:
    desc: Run day 2
    deps: [build]
    cmds: 
      - .lake/build/bin/day2