version: '3'

tasks:
  default: task --list
  build:
    desc: Build
    sources:
      - Aoc2024/**/*.lean
    generates:
      - .lake/build/bin/*
    cmds:
      - lake build
  day1:
    desc: Run day 1
    deps: [build]
    cmds: 
      - .lake/build/bin/day1
  day2:
    desc: Run day 2
    deps: [build]
    cmds: 
      - .lake/build/bin/day2
  day3:
    desc: Run day 3
    deps: [build]
    cmds: 
      - .lake/build/bin/day3
  day4:
    desc: Run day 4
    deps: [build]
    cmds: 
      - .lake/build/bin/day4
      
 